global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Application
  - job_name: 'basket-management'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 10s

  # TimescaleDB (if exposing metrics)
  - job_name: 'timescaledb'
    static_configs:
      - targets: ['basket-timescaledb:5432']
    scrape_interval: 30s

  # Redis (if exposing metrics)
  - job_name: 'redis'
    static_configs:
      - targets: ['basket-redis:6379']
    scrape_interval: 30s

  # Kafka (if exposing metrics)
  - job_name: 'kafka'
    static_configs:
      - targets: ['basket-kafka:9092']
Q:q!\q!    scrape_interval: 30s

  # Custom metrics endpoints
  - job_name: 'basket-metrics'
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 15s
